apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hexabase-docs-prod

namespace: hexabase-docs-prod

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

images:
- name: hexabase-ai/docs
  newTag: v1.0.0

commonLabels:
  environment: production

replicas:
- name: hexabase-docs
  count: 5