apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexabase-docs
  labels:
    app: hexabase-docs
    component: documentation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hexabase-docs
  template:
    metadata:
      labels:
        app: hexabase-docs
        component: documentation
    spec:
      containers:
      - name: docs
        image: hexabase-ai/docs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: NGINX_PORT
          value: "80"
        volumeMounts:
        - name: docs-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: docs-content
        configMap:
          name: hexabase-docs-content