apiVersion: v1
kind: ConfigMap
metadata:
  name: hexabase-docs-content
  labels:
    app: hexabase-docs
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hexabase.AI Documentation</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 40px;
                background-color: #000;
                color: #00C6AB;
            }
            h1 { color: #00C6AB; }
            .notice {
                background-color: #111;
                border: 2px solid #00C6AB;
                padding: 20px;
                border-radius: 8px;
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <h1>Hexabase.AI Documentation</h1>
        <div class="notice">
            <h2>Documentation Site Setup in Progress</h2>
            <p>The Hexabase.AI documentation is being deployed to Kubernetes.</p>
            <p>Once DNS is configured and SSL certificates are provisioned, the full documentation will be available here.</p>
            <ul>
                <li>Domain: docs.hexabase.ai</li>
                <li>SSL: Let's Encrypt (pending DNS configuration)</li>
                <li>Status: Deployment successful, awaiting DNS setup</li>
            </ul>
        </div>
    </body>
    </html>