apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hexabase-docs-base

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- hpa.yaml

commonLabels:
  app: hexabase-docs
  version: v1.0.0

images:
- name: hexabase-ai/docs
  newTag: latest